"""Idempotent seeder for the goods_catalog table with Chiikawa-family items.

Data sourced from public store fronts (chiikawamarket.jp, nagano-market.jp,
chiikawamogumogu.shop, chiikawa-pocket-goods-store.com, Chiikawa Park) plus
common known SKUs. Names are stored in Korean by default with Japanese and
English variants where available; prices are the listed JPY official prices
at time of seeding and may drift.

Run from the server directory:
    python -m seed_chiikawa
or:
    python seed_chiikawa.py
"""

from __future__ import annotations

from typing import Iterable

from app.db import Base, SessionLocal, engine
from app.models import GoodsCatalog


SEED_DATA: list[dict[str, object]] = [
    # ── Chiikawa Market ─────────────────────────────────────────────────
    {
        "name_ko": "치이카와 발수 백팩 (모두)",
        "name_ja": "ちいかわ 撥水バックパック (みんな)",
        "name_en": "Chiikawa Water-Resistant Backpack",
        "category": "백팩",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와 마켓",
        "official_price_jpy": 7260,
        "source_url": "https://chiikawamarket.jp/ko",
        "source_store": "치이카와 마켓",
    },
    {
        "name_ko": "치이카와 클리어 토트백 (비가 오네 / 라이트 블루)",
        "name_ja": "ちいかわ クリアトートバッグ (雨だね/ライトブルー)",
        "name_en": "Chiikawa Clear Tote Bag (Rain / Light Blue)",
        "category": "토트백",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와 마켓",
        "official_price_jpy": 4950,
        "source_url": "https://chiikawamarket.jp/ko",
        "source_store": "치이카와 마켓",
    },
    {
        "name_ko": "치이카와 클리어 토트백 (고글 토끼 / 화이트)",
        "name_ja": "ちいかわ クリアトートバッグ (ゴーグルうさぎ/ホワイト)",
        "name_en": "Chiikawa Clear Tote Bag (Goggle Usagi / White)",
        "category": "토트백",
        "character_name": "우사기",
        "affiliation": "치이카와",
        "series_name": "치이카와 마켓",
        "official_price_jpy": 4950,
        "source_url": "https://chiikawamarket.jp/ko",
        "source_store": "치이카와 마켓",
    },
    {
        "name_ko": "치이카와 패커블 레인 판초 (개구리 모두 / 차콜)",
        "name_ja": "ちいかわ パッカブルレインポンチョ (カエルみんな/チャコール)",
        "category": "레인웨어",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와 마켓",
        "official_price_jpy": 4950,
        "source_url": "https://chiikawamarket.jp/ko",
        "source_store": "치이카와 마켓",
    },
    {
        "name_ko": "치이카와 패커블 레인 판초 (우라야하보즈 토끼 / 베이지)",
        "name_ja": "ちいかわ パッカブルレインポンチョ (うらやはぼずうさぎ/ベージュ)",
        "category": "레인웨어",
        "character_name": "우사기",
        "affiliation": "치이카와",
        "series_name": "치이카와 마켓",
        "official_price_jpy": 4950,
        "source_url": "https://chiikawamarket.jp/ko",
        "source_store": "치이카와 마켓",
    },
    {
        "name_ko": "치이카와 애니메이션 암 가드 NAVY",
        "name_ja": "ちいかわ アニメ アームガード NAVY",
        "category": "액세서리",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와 애니메이션",
        "official_price_jpy": 1100,
        "source_url": "https://chiikawamarket.jp/ko",
        "source_store": "치이카와 마켓",
    },
    {
        "name_ko": "치이카와 애니메이션 메쉬 캡 PINK",
        "name_ja": "ちいかわ アニメ メッシュキャップ PINK",
        "category": "모자",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와 애니메이션",
        "official_price_jpy": 2178,
        "source_url": "https://chiikawamarket.jp/ko",
        "source_store": "치이카와 마켓",
    },
    {
        "name_ko": "치이카와 맨해튼 포티지 백팩 2285JR",
        "name_ja": "ちいかわ Manhattan Portage バックパック 2285JR",
        "category": "백팩",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와 × Manhattan Portage",
        "official_price_jpy": 24200,
        "source_url": "https://chiikawamarket.jp/ko",
        "source_store": "치이카와 마켓",
    },
    {
        "name_ko": "Chiikawa Baby 마스코트 (우사기)",
        "name_ja": "ちいかわベビー マスコット (うさぎ)",
        "category": "마스코트",
        "character_name": "우사기",
        "affiliation": "치이카와",
        "series_name": "Chiikawa Baby",
        "sub_series": "마스코트",
        "official_price_jpy": 1540,
        "source_url": "https://chiikawamarket.jp/ko",
        "source_store": "치이카와 마켓",
    },
    {
        "name_ko": "매지컬 치이카와 쁘띠 미니 마스코트 (치이카와)",
        "name_ja": "マジカルちいかわ プチミニマスコット (ちいかわ)",
        "category": "마스코트",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "매지컬 치이카와",
        "official_price_jpy": 1870,
        "source_url": "https://chiikawamarket.jp/ko",
        "source_store": "치이카와 마켓",
    },
    # ── Nagano Market ───────────────────────────────────────────────────
    {
        "name_ko": "나가노 캐릭터즈 클리어 토트백 (블루 레인)",
        "name_ja": "ナガノキャラクターズ クリアトートバッグ (ブルーレイン)",
        "category": "토트백",
        "character_name": "나가노 캐릭터즈",
        "affiliation": "나가노 캐릭터즈",
        "series_name": "나가노 마켓",
        "official_price_jpy": 4950,
        "source_url": "https://nagano-market.jp/ko",
        "source_store": "나가노 마켓",
    },
    {
        "name_ko": "나가노 캐릭터즈 메쉬 숄더백 (검정 / 곰)",
        "name_ja": "ナガノキャラクターズ メッシュショルダーバッグ (ブラック/くま)",
        "category": "숄더백",
        "character_name": "곰",
        "affiliation": "나가노 캐릭터즈",
        "series_name": "나가노 마켓",
        "official_price_jpy": 2970,
        "source_url": "https://nagano-market.jp/ko",
        "source_store": "나가노 마켓",
    },
    {
        "name_ko": "나가노 캐릭터즈 메쉬 숄더백 (카키 / 두더지)",
        "name_ja": "ナガノキャラクターズ メッシュショルダーバッグ (カーキ/モグラ)",
        "category": "숄더백",
        "character_name": "두더지",
        "affiliation": "나가노 캐릭터즈",
        "series_name": "나가노 마켓",
        "official_price_jpy": 2970,
        "source_url": "https://nagano-market.jp/ko",
        "source_store": "나가노 마켓",
    },
    {
        "name_ko": "나가노 캐릭터즈 우는 마스코트",
        "name_ja": "ナガノキャラクターズ 泣いてるマスコット",
        "category": "마스코트",
        "character_name": "나가노 캐릭터즈",
        "affiliation": "나가노 캐릭터즈",
        "series_name": "나가노 마켓",
        "official_price_jpy": 1650,
        "source_url": "https://nagano-market.jp/ko",
        "source_store": "나가노 마켓",
    },
    {
        "name_ko": "나가노 캐릭터즈 후드 추파카브라 마스코트",
        "name_ja": "ナガノキャラクターズ パーカーチュパカブラマスコット",
        "category": "마스코트",
        "character_name": "추파카브라",
        "affiliation": "나가노 캐릭터즈",
        "series_name": "나가노 마켓",
        "official_price_jpy": 1870,
        "source_url": "https://nagano-market.jp/ko",
        "source_store": "나가노 마켓",
    },
    {
        "name_ko": "나가노 캐릭터즈 친칠라 마스코트",
        "name_ja": "ナガノキャラクターズ チンチラマスコット",
        "category": "마스코트",
        "character_name": "친칠라",
        "affiliation": "나가노 캐릭터즈",
        "series_name": "나가노 마켓",
        "official_price_jpy": 1760,
        "source_url": "https://nagano-market.jp/ko",
        "source_store": "나가노 마켓",
    },
    {
        "name_ko": "나가노 캐릭터즈 졸음 마스코트",
        "name_ja": "ナガノキャラクターズ うとうとマスコット",
        "category": "마스코트",
        "character_name": "나가노 캐릭터즈",
        "affiliation": "나가노 캐릭터즈",
        "series_name": "나가노 마켓",
        "official_price_jpy": 1760,
        "source_url": "https://nagano-market.jp/ko",
        "source_store": "나가노 마켓",
    },
    {
        "name_ko": "나가노 캐릭터즈 발수 접시 (피자)",
        "name_ja": "ナガノキャラクターズ 撥水プレート (ピザ)",
        "category": "식기",
        "character_name": "나가노 캐릭터즈",
        "affiliation": "나가노 캐릭터즈",
        "series_name": "나가노 마켓",
        "sub_series": "발수 식기",
        "official_price_jpy": 2090,
        "source_url": "https://nagano-market.jp/ko",
        "source_store": "나가노 마켓",
    },
    {
        "name_ko": "나가노 캐릭터즈 발수 접시 (빛나는 곰)",
        "name_ja": "ナガノキャラクターズ 撥水プレート (光るくま)",
        "category": "식기",
        "character_name": "곰",
        "affiliation": "나가노 캐릭터즈",
        "series_name": "나가노 마켓",
        "sub_series": "발수 식기",
        "official_price_jpy": 2090,
        "source_url": "https://nagano-market.jp/ko",
        "source_store": "나가노 마켓",
    },
    {
        "name_ko": "나가노 캐릭터즈 발수 머그 (안심감)",
        "name_ja": "ナガノキャラクターズ 撥水マグ (安心感)",
        "category": "머그컵",
        "character_name": "나가노 캐릭터즈",
        "affiliation": "나가노 캐릭터즈",
        "series_name": "나가노 마켓",
        "sub_series": "발수 식기",
        "official_price_jpy": 2420,
        "source_url": "https://nagano-market.jp/ko",
        "source_store": "나가노 마켓",
    },
    {
        "name_ko": "나가노 캐릭터즈 발수 머그 (민들레)",
        "name_ja": "ナガノキャラクターズ 撥水マグ (タンポポ)",
        "category": "머그컵",
        "character_name": "나가노 캐릭터즈",
        "affiliation": "나가노 캐릭터즈",
        "series_name": "나가노 마켓",
        "sub_series": "발수 식기",
        "official_price_jpy": 2420,
        "source_url": "https://nagano-market.jp/ko",
        "source_store": "나가노 마켓",
    },
    # ── Chiikawa Park ───────────────────────────────────────────────────
    {
        "name_ko": "치이카와 파크 푸와코로 인형 S - 치이카와",
        "name_ja": "ちいかわパーク ぷわころぬいぐるみS ちいかわ",
        "category": "봉제 인형",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와 파크",
        "sub_series": "푸와코로 S",
        "official_price_jpy": 2420,
        "source_url": "https://chiikawamarket.jp/ko/pages/chiikawapark",
        "source_store": "치이카와 파크",
    },
    {
        "name_ko": "치이카와 파크 푸와코로 인형 S - 하치와레",
        "name_ja": "ちいかわパーク ぷわころぬいぐるみS ハチワレ",
        "category": "봉제 인형",
        "character_name": "하치와레",
        "affiliation": "치이카와",
        "series_name": "치이카와 파크",
        "sub_series": "푸와코로 S",
        "official_price_jpy": 2420,
        "source_url": "https://chiikawamarket.jp/ko/pages/chiikawapark",
        "source_store": "치이카와 파크",
    },
    {
        "name_ko": "치이카와 파크 푸와코로 인형 S - 우사기",
        "name_ja": "ちいかわパーク ぷわころぬいぐるみS うさぎ",
        "category": "봉제 인형",
        "character_name": "우사기",
        "affiliation": "치이카와",
        "series_name": "치이카와 파크",
        "sub_series": "푸와코로 S",
        "official_price_jpy": 2420,
        "source_url": "https://chiikawamarket.jp/ko/pages/chiikawapark",
        "source_store": "치이카와 파크",
    },
    {
        "name_ko": "치이카와 파크 푸와코로 인형 S - 모몽가",
        "name_ja": "ちいかわパーク ぷわころぬいぐるみS モモンガ",
        "category": "봉제 인형",
        "character_name": "모몽가",
        "affiliation": "치이카와",
        "series_name": "치이카와 파크",
        "sub_series": "푸와코로 S",
        "official_price_jpy": 2420,
        "source_url": "https://chiikawamarket.jp/ko/pages/chiikawapark",
        "source_store": "치이카와 파크",
    },
    {
        "name_ko": "치이카와 파크 푸와코로 인형 S - 쿠리만쥬",
        "name_ja": "ちいかわパーク ぷわころぬいぐるみS くりまんじゅう",
        "category": "봉제 인형",
        "character_name": "쿠리만쥬",
        "affiliation": "치이카와",
        "series_name": "치이카와 파크",
        "sub_series": "푸와코로 S",
        "official_price_jpy": 2420,
        "source_url": "https://chiikawamarket.jp/ko/pages/chiikawapark",
        "source_store": "치이카와 파크",
    },
    {
        "name_ko": "치이카와 파크 푸와코로 인형 S - 시사",
        "name_ja": "ちいかわパーク ぷわころぬいぐるみS シーサー",
        "category": "봉제 인형",
        "character_name": "시사",
        "affiliation": "치이카와",
        "series_name": "치이카와 파크",
        "sub_series": "푸와코로 S",
        "official_price_jpy": 2420,
        "source_url": "https://chiikawamarket.jp/ko/pages/chiikawapark",
        "source_store": "치이카와 파크",
    },
    {
        "name_ko": "치이카와 파크 푸와코로 인형 S - 책방 주인",
        "name_ja": "ちいかわパーク ぷわころぬいぐるみS 本屋さん",
        "category": "봉제 인형",
        "character_name": "책방 주인",
        "affiliation": "치이카와",
        "series_name": "치이카와 파크",
        "sub_series": "푸와코로 S",
        "official_price_jpy": 2420,
        "source_url": "https://chiikawamarket.jp/ko/pages/chiikawapark",
        "source_store": "치이카와 파크",
    },
    {
        "name_ko": "치이카와 파크 무챠우만 폭신 인형",
        "name_ja": "ちいかわパーク むちゃうマンぷわぷわぬいぐるみ",
        "category": "봉제 인형",
        "character_name": "무챠우만",
        "affiliation": "치이카와",
        "series_name": "치이카와 파크",
        "official_price_jpy": 2530,
        "source_url": "https://chiikawamarket.jp/ko/pages/chiikawapark",
        "source_store": "치이카와 파크",
    },
    {
        "name_ko": "치이카와 파크 안기 쿠션 (테디베어 치이카와)",
        "name_ja": "ちいかわパーク だっこクッション (テディベアちいかわ)",
        "category": "쿠션",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와 파크",
        "official_price_jpy": 3630,
        "source_url": "https://chiikawamarket.jp/ko/pages/chiikawapark",
        "source_store": "치이카와 파크",
    },
    {
        "name_ko": "치이카와 파크 안기 쿠션 (카부토무시)",
        "name_ja": "ちいかわパーク だっこクッション (カブトムシ)",
        "category": "쿠션",
        "character_name": "카부토무시",
        "affiliation": "치이카와",
        "series_name": "치이카와 파크",
        "official_price_jpy": 3630,
        "source_url": "https://chiikawamarket.jp/ko/pages/chiikawapark",
        "source_store": "치이카와 파크",
    },
    {
        "name_ko": "치이카와 파크 우키우키 마스코트 모자",
        "name_ja": "ちいかわパーク うきうきマスコットハット",
        "category": "모자",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와 파크",
        "official_price_jpy": 1210,
        "source_url": "https://chiikawamarket.jp/ko/pages/chiikawapark",
        "source_store": "치이카와 파크",
    },
    {
        "name_ko": "치이카와 파크 우키우키 인형 모자",
        "name_ja": "ちいかわパーク うきうきぬいぐるみハット",
        "category": "모자",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와 파크",
        "official_price_jpy": 3520,
        "source_url": "https://chiikawamarket.jp/ko/pages/chiikawapark",
        "source_store": "치이카와 파크",
    },
    # ── Chiikawa Mogumogu Honpo ─────────────────────────────────────────
    {
        "name_ko": "치이카와 모구모구 와소 끈 파우치",
        "name_ja": "ちいかわもぐもぐ 和装巾着ポーチ",
        "category": "파우치",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와모구모구혼포",
        "sub_series": "와소",
        "official_price_jpy": 1320,
        "source_url": "https://chiikawamogumogu.shop/",
        "source_store": "치이카와 모구모구 혼포",
    },
    {
        "name_ko": "치이카와 모구모구 와소 스티커",
        "name_ja": "ちいかわもぐもぐ 和装ステッカー",
        "category": "스티커",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와모구모구혼포",
        "sub_series": "와소",
        "official_price_jpy": 330,
        "source_url": "https://chiikawamogumogu.shop/",
        "source_store": "치이카와 모구모구 혼포",
    },
    {
        "name_ko": "치이카와 모구모구 와소 메모지",
        "name_ja": "ちいかわもぐもぐ 和装メモ帳",
        "category": "문구",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와모구모구혼포",
        "sub_series": "와소",
        "official_price_jpy": 440,
        "source_url": "https://chiikawamogumogu.shop/",
        "source_store": "치이카와 모구모구 혼포",
    },
    {
        "name_ko": "치이카와 모구모구 와소 젓가락",
        "name_ja": "ちいかわもぐもぐ 和装お箸",
        "category": "식기",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와모구모구혼포",
        "sub_series": "와소",
        "official_price_jpy": 1320,
        "source_url": "https://chiikawamogumogu.shop/",
        "source_store": "치이카와 모구모구 혼포",
    },
    {
        "name_ko": "치이카와 모구모구 와소 스마트폰 스티커",
        "name_ja": "ちいかわもぐもぐ 和装スマホステッカー",
        "category": "스티커",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와모구모구혼포",
        "sub_series": "와소",
        "official_price_jpy": 440,
        "source_url": "https://chiikawamogumogu.shop/",
        "source_store": "치이카와 모구모구 혼포",
    },
    # ── Chiikawa Pocket Goods Store (general known SKUs) ────────────────
    {
        "name_ko": "치이카와 봉제 인형 S - 치이카와",
        "name_ja": "ちいかわ ぬいぐるみS ちいかわ",
        "category": "봉제 인형",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와포켓토",
        "official_price_jpy": 1650,
        "source_url": "https://chiikawa-pocket-goods-store.com/",
        "source_store": "치이카와 포켓토",
    },
    {
        "name_ko": "치이카와 봉제 인형 S - 하치와레",
        "name_ja": "ちいかわ ぬいぐるみS ハチワレ",
        "category": "봉제 인형",
        "character_name": "하치와레",
        "affiliation": "치이카와",
        "series_name": "치이카와포켓토",
        "official_price_jpy": 1650,
        "source_url": "https://chiikawa-pocket-goods-store.com/",
        "source_store": "치이카와 포켓토",
    },
    {
        "name_ko": "치이카와 봉제 인형 S - 우사기",
        "name_ja": "ちいかわ ぬいぐるみS うさぎ",
        "category": "봉제 인형",
        "character_name": "우사기",
        "affiliation": "치이카와",
        "series_name": "치이카와포켓토",
        "official_price_jpy": 1650,
        "source_url": "https://chiikawa-pocket-goods-store.com/",
        "source_store": "치이카와 포켓토",
    },
    {
        "name_ko": "치이카와 캔뱃지 (랜덤)",
        "name_ja": "ちいかわ 缶バッジ (ランダム)",
        "category": "캔뱃지",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와포켓토",
        "official_price_jpy": 440,
        "source_url": "https://chiikawa-pocket-goods-store.com/",
        "source_store": "치이카와 포켓토",
    },
    {
        "name_ko": "치이카와 아크릴 키링 - 치이카와",
        "name_ja": "ちいかわ アクリルキーホルダー ちいかわ",
        "category": "키링",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와포켓토",
        "official_price_jpy": 770,
        "source_url": "https://chiikawa-pocket-goods-store.com/",
        "source_store": "치이카와 포켓토",
    },
    {
        "name_ko": "치이카와 아크릴 키링 - 하치와레",
        "name_ja": "ちいかわ アクリルキーホルダー ハチワレ",
        "category": "키링",
        "character_name": "하치와레",
        "affiliation": "치이카와",
        "series_name": "치이카와포켓토",
        "official_price_jpy": 770,
        "source_url": "https://chiikawa-pocket-goods-store.com/",
        "source_store": "치이카와 포켓토",
    },
    {
        "name_ko": "치이카와 트레이딩 아크릴 스탠드 (랜덤)",
        "name_ja": "ちいかわ トレーディングアクリルスタンド (ランダム)",
        "category": "아크릴 스탠드",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와포켓토",
        "official_price_jpy": 770,
        "source_url": "https://chiikawa-pocket-goods-store.com/",
        "source_store": "치이카와 포켓토",
    },
    {
        "name_ko": "치이카와 클리어 파일 A4",
        "name_ja": "ちいかわ クリアファイル A4",
        "category": "문구",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와포켓토",
        "official_price_jpy": 440,
        "source_url": "https://chiikawa-pocket-goods-store.com/",
        "source_store": "치이카와 포켓토",
    },
    {
        "name_ko": "치이카와 머그컵",
        "name_ja": "ちいかわ マグカップ",
        "category": "머그컵",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와포켓토",
        "official_price_jpy": 1650,
        "source_url": "https://chiikawa-pocket-goods-store.com/",
        "source_store": "치이카와 포켓토",
    },
    {
        "name_ko": "치이카와 일러스트 트레이딩 카드 (랜덤 1팩)",
        "name_ja": "ちいかわ イラスト トレーディングカード (ランダム1パック)",
        "category": "트레이딩 카드",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와포켓토",
        "official_price_jpy": 330,
        "source_url": "https://chiikawa-pocket-goods-store.com/",
        "source_store": "치이카와 포켓토",
    },
    {
        "name_ko": "치이카와 T셔츠",
        "name_ja": "ちいかわ Tシャツ",
        "category": "의류",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와포켓토",
        "official_price_jpy": 3300,
        "source_url": "https://chiikawa-pocket-goods-store.com/",
        "source_store": "치이카와 포켓토",
    },
    {
        "name_ko": "치이카와 토트백 (소)",
        "name_ja": "ちいかわ トートバッグ (S)",
        "category": "토트백",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와포켓토",
        "official_price_jpy": 2200,
        "source_url": "https://chiikawa-pocket-goods-store.com/",
        "source_store": "치이카와 포켓토",
    },
    {
        "name_ko": "치이카와 후시미 한정 굿즈 (교토)",
        "name_ja": "ちいかわ 伏見限定グッズ (京都)",
        "category": "한정 굿즈",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와모구모구혼포",
        "sub_series": "후시미",
        "official_price_jpy": None,
        "source_url": "https://chiikawamogumogu.shop/",
        "source_store": "치이카와 모구모구 혼포",
    },
    {
        "name_ko": "치이카와 카와고에 한정 굿즈 (사이타마)",
        "name_ja": "ちいかわ 川越限定グッズ (埼玉)",
        "category": "한정 굿즈",
        "character_name": "치이카와",
        "affiliation": "치이카와",
        "series_name": "치이카와모구모구혼포",
        "sub_series": "카와고에",
        "official_price_jpy": None,
        "source_url": "https://chiikawamogumogu.shop/",
        "source_store": "치이카와 모구모구 혼포",
    },
]


def _upsert(items: Iterable[dict[str, object]]) -> int:
    """Insert items whose `name_ko` does not exist yet. Returns inserted count."""
    inserted = 0
    db = SessionLocal()
    try:
        existing = {
            row[0]
            for row in db.query(GoodsCatalog.name_ko).all()
        }
        for spec in items:
            if spec["name_ko"] in existing:
                continue
            entry = GoodsCatalog(**spec)  # type: ignore[arg-type]
            db.add(entry)
            inserted += 1
        if inserted:
            db.commit()
    finally:
        db.close()
    return inserted


def main() -> None:
    Base.metadata.create_all(bind=engine)
    inserted = _upsert(SEED_DATA)
    total = len(SEED_DATA)
    print(f"seeded {inserted}/{total} chiikawa goods (rest were already present)")


if __name__ == "__main__":
    main()
