import 'package:flutter/material.dart';

/// Reserved id for the auto-created system wishlist folder.
const String kSystemWishlistFolderId = '__system_wishlist__';

class FolderItem {
  final String id;
  final String name;
  final IconData icon;
  final Color color;
  final bool isGroup;
  final String? parentId;
  final bool isSystemWishlist;

  const FolderItem({
    required this.id,
    required this.name,
    required this.icon,
    required this.color,
    this.isGroup = false,
    this.parentId,
    this.isSystemWishlist = false,
  });

  FolderItem copyWith({
    String? id,
    String? name,
    IconData? icon,
    Color? color,
    bool? isGroup,
    Object? parentId = _copyWithSentinel,
    bool? isSystemWishlist,
  }) {
    return FolderItem(
      id: id ?? this.id,
      name: name ?? this.name,
      icon: icon ?? this.icon,
      color: color ?? this.color,
      isGroup: isGroup ?? this.isGroup,
      parentId: identical(parentId, _copyWithSentinel)
          ? this.parentId
          : parentId as String?,
      isSystemWishlist: isSystemWishlist ?? this.isSystemWishlist,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'iconCodePoint': icon.codePoint,
      'iconFontFamily': icon.fontFamily,
      'iconFontPackage': icon.fontPackage,
      'color': color.toARGB32(),
      'isGroup': isGroup,
      'parentId': parentId,
      'isSystemWishlist': isSystemWishlist,
    };
  }

  factory FolderItem.fromJson(Map<String, dynamic> json) {
    final iconCodePoint =
        json['iconCodePoint'] as int? ?? Icons.folder_rounded.codePoint;
    return FolderItem(
      id: json['id'] as String? ?? '',
      name: json['name'] as String? ?? '',
      icon: _iconFromCodePoint(iconCodePoint),
      color: Color(json['color'] as int? ?? const Color(0xFF87CEEB).toARGB32()),
      isGroup: json['isGroup'] as bool? ?? false,
      parentId: json['parentId'] as String?,
      isSystemWishlist: json['isSystemWishlist'] as bool? ?? false,
    );
  }
}

IconData _iconFromCodePoint(int codePoint) {
  // The deprecated icons (redeem / photo_library / palette / workspace_premium)
  // are kept here so folders saved before the catalog refresh still render
  // correctly — they just can't be picked from the editor anymore.
  for (final icon in _knownIcons) {
    if (codePoint == icon.codePoint) return icon;
  }
  return Icons.folder_rounded;
}

const List<IconData> _knownIcons = [
  Icons.folder_open_rounded,
  Icons.create_new_folder_rounded,
  Icons.source_rounded,
  Icons.playlist_add_check_rounded,
  Icons.task_alt_rounded,
  Icons.done_all_rounded,
  Icons.pending_actions_rounded,
  Icons.assignment_rounded,
  Icons.assignment_turned_in_rounded,
  Icons.view_column_rounded,
  Icons.space_dashboard_rounded,
  Icons.shopping_basket_rounded,
  Icons.add_shopping_cart_rounded,
  Icons.production_quantity_limits_rounded,
  Icons.request_quote_rounded,
  Icons.currency_yen_rounded,
  Icons.currency_exchange_rounded,
  Icons.credit_card_rounded,
  Icons.local_atm_rounded,
  Icons.perm_media_rounded,
  Icons.wallpaper_rounded,
  Icons.portrait_rounded,
  Icons.mood_rounded,
  Icons.emoji_emotions_rounded,
  Icons.sentiment_very_satisfied_rounded,
  Icons.child_care_rounded,
  Icons.interests_rounded,
  Icons.token_rounded,
  Icons.queue_music_rounded,
  Icons.library_music_rounded,
  Icons.videogame_asset_rounded,
  Icons.lunch_dining_rounded,
  Icons.set_meal_rounded,

  // Current catalog
  Icons.folder_rounded,
  Icons.folder_copy_rounded,
  Icons.folder_special_rounded,
  Icons.cloud_rounded,
  Icons.inventory_2_rounded,
  Icons.category_rounded,
  Icons.bookmark_rounded,
  Icons.bookmark_added_rounded,
  Icons.label_rounded,
  Icons.label_important_rounded,
  Icons.archive_rounded,
  Icons.unarchive_rounded,
  Icons.inbox_rounded,
  Icons.move_to_inbox_rounded,
  Icons.all_inbox_rounded,
  Icons.fact_check_rounded,
  Icons.checklist_rounded,
  Icons.rule_rounded,
  Icons.dashboard_rounded,
  Icons.analytics_rounded,
  Icons.bar_chart_rounded,
  Icons.view_stream_rounded,
  Icons.table_bar_rounded,
  Icons.view_kanban_rounded,
  Icons.view_agenda_rounded,
  Icons.widgets_rounded,
  Icons.dataset_rounded,
  Icons.view_module_rounded,
  Icons.view_list_rounded,
  Icons.table_rows_rounded,
  Icons.shopping_bag_rounded,
  Icons.backpack_rounded,
  Icons.dry_cleaning_rounded,
  Icons.local_laundry_service_rounded,
  Icons.coffee_rounded,
  Icons.account_balance_wallet_rounded,
  Icons.sell_rounded,
  Icons.local_offer_rounded,
  Icons.discount_rounded,
  Icons.loyalty_rounded,
  Icons.redeem_rounded,
  Icons.card_giftcard_rounded,
  Icons.confirmation_number_rounded,
  Icons.local_activity_rounded,
  Icons.shopping_cart_rounded,
  Icons.local_shipping_rounded,
  Icons.inventory_rounded,
  Icons.warehouse_rounded,
  Icons.payments_rounded,
  Icons.paid_rounded,
  Icons.receipt_long_rounded,
  Icons.price_check_rounded,
  Icons.card_membership_rounded,
  Icons.savings_rounded,
  Icons.qr_code_2_rounded,
  Icons.bubble_chart_rounded,
  Icons.military_tech_rounded,
  Icons.key_rounded,
  Icons.vpn_key_rounded,
  Icons.watch_rounded,
  Icons.radio_button_checked_rounded,
  Icons.photo_library_rounded,
  Icons.photo_rounded,
  Icons.photo_camera_back_rounded,
  Icons.collections_rounded,
  Icons.collections_bookmark_rounded,
  Icons.view_carousel_rounded,
  Icons.filter_frames_rounded,
  Icons.burst_mode_rounded,
  Icons.panorama_rounded,
  Icons.screenshot_rounded,
  Icons.document_scanner_rounded,
  Icons.center_focus_strong_rounded,
  Icons.add_photo_alternate_rounded,
  Icons.slideshow_rounded,
  Icons.photo_camera_rounded,
  Icons.image_rounded,
  Icons.image_search_rounded,
  Icons.filter_rounded,
  Icons.compare_rounded,
  Icons.grid_view_rounded,
  Icons.view_comfy_rounded,
  Icons.view_in_ar_rounded,
  Icons.file_copy_rounded,
  Icons.view_quilt_rounded,
  Icons.web_asset_rounded,
  Icons.apps_rounded,
  Icons.filter_none_rounded,
  Icons.image_aspect_ratio_rounded,
  Icons.markunread_mailbox_rounded,
  Icons.card_travel_rounded,
  Icons.work_rounded,
  Icons.new_releases_rounded,
  Icons.swap_horiz_rounded,
  Icons.handshake_rounded,
  Icons.event_available_rounded,
  Icons.price_change_rounded,
  Icons.favorite_rounded,
  Icons.favorite_border_rounded,
  Icons.star_rounded,
  Icons.auto_awesome_rounded,
  Icons.diamond_rounded,
  Icons.celebration_rounded,
  Icons.stars_rounded,
  Icons.emoji_events_rounded,
  Icons.workspace_premium_rounded,
  Icons.verified_rounded,
  Icons.shield_rounded,
  Icons.security_rounded,
  Icons.push_pin_rounded,
  Icons.bolt_rounded,
  Icons.flag_rounded,
  Icons.history_rounded,
  Icons.emoji_objects_rounded,
  Icons.local_fire_department_rounded,
  Icons.visibility_rounded,
  Icons.lock_rounded,
  Icons.lock_open_rounded,
  Icons.check_box_rounded,
  Icons.remove_shopping_cart_rounded,
  Icons.outbox_rounded,
  Icons.face_rounded,
  Icons.person_rounded,
  Icons.person_pin_rounded,
  Icons.groups_rounded,
  Icons.diversity_2_rounded,
  Icons.theater_comedy_rounded,
  Icons.pets_rounded,
  Icons.toys_rounded,
  Icons.smart_toy_rounded,
  Icons.badge_rounded,
  Icons.style_rounded,
  Icons.checkroom_rounded,
  Icons.emoji_people_rounded,
  Icons.diversity_3_rounded,
  Icons.accessibility_new_rounded,
  Icons.record_voice_over_rounded,
  Icons.face_retouching_natural_rounded,
  Icons.extension_rounded,
  Icons.attractions_rounded,
  Icons.sports_mma_rounded,
  Icons.casino_rounded,
  Icons.music_note_rounded,
  Icons.album_rounded,
  Icons.headphones_rounded,
  Icons.sports_esports_rounded,
  Icons.book_rounded,
  Icons.local_library_rounded,
  Icons.auto_stories_rounded,
  Icons.menu_book_rounded,
  Icons.sticky_note_2_rounded,
  Icons.edit_note_rounded,
  Icons.draw_rounded,
  Icons.school_rounded,
  Icons.palette_rounded,
  Icons.brush_rounded,
  Icons.movie_rounded,
  Icons.animation_rounded,
  Icons.movie_filter_rounded,
  Icons.live_tv_rounded,
  Icons.mic_rounded,
  Icons.campaign_rounded,
  Icons.flashlight_on_rounded,
  Icons.podcasts_rounded,
  Icons.lyrics_rounded,
  Icons.local_cafe_rounded,
  Icons.cake_rounded,
  Icons.bakery_dining_rounded,
  Icons.cookie_rounded,
  Icons.icecream_rounded,
  Icons.ramen_dining_rounded,
  Icons.restaurant_rounded,
  Icons.restaurant_menu_rounded,
  Icons.local_drink_rounded,
  Icons.fastfood_rounded,
  Icons.storefront_rounded,
  Icons.place_rounded,
  Icons.pin_drop_rounded,
  Icons.explore_rounded,
  Icons.route_rounded,
  Icons.map_rounded,
  Icons.home_rounded,
  Icons.local_mall_rounded,
  Icons.museum_rounded,
  Icons.festival_rounded,
  Icons.theaters_rounded,
  Icons.flight_takeoff_rounded,
  Icons.calendar_month_rounded,
  Icons.event_rounded,
  Icons.event_note_rounded,
  Icons.date_range_rounded,
  Icons.schedule_rounded,
  Icons.article_rounded,
  Icons.feed_rounded,
  Icons.forum_rounded,
  Icons.chat_bubble_rounded,
  Icons.mail_rounded,
  Icons.newspaper_rounded,
  Icons.notifications_rounded,
  Icons.today_rounded,
  Icons.alarm_rounded,
  Icons.check_circle_rounded,
  Icons.history_rounded,
  Icons.update_rounded,
  Icons.local_florist_rounded,
  Icons.spa_rounded,
  Icons.park_rounded,
  Icons.wb_sunny_rounded,
  Icons.nightlight_rounded,
  Icons.rocket_launch_rounded,
  Icons.travel_explore_rounded,
  Icons.cloud_queue_rounded,
  Icons.water_drop_rounded,
];

const Object _copyWithSentinel = Object();
