from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_INPUT = ROOT / "server" / "catalog_image_exact_url_confirmed.template.json"
DEFAULT_OUTPUT = ROOT / "server" / "catalog_image_exact_url_confirmed.import.json"


def _confirmed(value: Any) -> bool:
    return str(value or "").strip().lower() in {"1", "true", "yes", "y", "confirmed", "확인", "확정"}


def _items(payload: Any) -> list[dict[str, Any]]:
    raw_items = payload.get("items") if isinstance(payload, dict) else payload
    if not isinstance(raw_items, list):
        raise SystemExit("Input must be a JSON list or an object with an items list")
    return [item for item in raw_items if isinstance(item, dict)]


def build_import_queue(items: list[dict[str, Any]]) -> dict[str, Any]:
    ready: list[dict[str, Any]] = []
    skipped: list[dict[str, Any]] = []
    seen_rows: set[int] = set()

    for item in items:
        row_index = item.get("row_index")
        if not isinstance(row_index, int) or isinstance(row_index, bool):
            skipped.append({"row_index": row_index, "reason": "invalid_row_index"})
            continue
        if row_index in seen_rows:
            skipped.append({"row_index": row_index, "reason": "duplicate_row_index"})
            continue
        if not _confirmed(item.get("manual_confirmed")):
            skipped.append({"row_index": row_index, "reason": "manual_confirmed_false"})
            continue
        source_url = str(item.get("source_url") or item.get("candidate_source_url") or "").strip()
        image_url = str(item.get("image_url") or item.get("candidate_image_url") or item.get("manual_value") or "").strip()
        if not source_url or not image_url:
            skipped.append({"row_index": row_index, "reason": "missing_source_or_image_url"})
            continue
        seen_rows.add(row_index)
        ready.append(
            {
                "row_index": row_index,
                "name_ko": item.get("name_ko"),
                "source_store": item.get("source_store"),
                "source_kind": item.get("source_kind") or "licensed_retailer_exact",
                "confidence": item.get("confidence") or 0.9,
                "source_url": source_url,
                "image_url": image_url,
                "candidate_title": item.get("candidate_title") or item.get("title") or "",
                "manual_confirmed": True,
            }
        )

    return {
        "instructions": [
            "Generated by tools/filter_confirmed_image_candidates.py.",
            "Import with tools/import_manual_image_candidates.py --candidates this_file --report ... after reviewing the dry-run report.",
        ],
        "items": ready,
        "summary": {
            "input_items": len(items),
            "ready_items": len(ready),
            "skipped_items": len(skipped),
        },
        "skipped_sample": skipped[:100],
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    payload = json.loads(args.input.read_text(encoding="utf-8-sig"))
    result = build_import_queue(_items(payload))
    args.output.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({**result["summary"], "output": str(args.output)}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
